### ISSUE TITLE
Does not work on Mono (Linux)

### ISSUE THREAD

**Issue by amedee** [IRnifty/KerbalConfigEditor#1]
I copied the exe to the Kerbal folder, renamed it to `kce.exe`, and ran it with `mono kce.exe`. This is what happened:
    amedee@saruman:~/.steam/steam/steamapps/common/Kerbal Space Program$ mono kce.exe

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

I have also scanned it with the Mono Migration Analyzer (MoMA) tool (http://www.mono-project.com/docs/tools+libraries/tools/moma/). That gave one issue, but I don't think it is related. I will create a separate github issue for that.

Ubuntu 14.10, Mono version:

```
$ mono --version | head -n 1
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu2)
```

**Comment by IRnifty** [comment]
This is likely due to this program performing file operations specifically using the Windows path syntax (backslashes instead of forward slashes). This program is currently not intended to operate on any other OS at this time. When I learn more about Mono and WinForms, I may change this.
