### ISSUE TITLE
Method with [MonoTodo]

### ISSUE THREAD

**Issue by amedee** [IRnifty/KerbalConfigEditor#2]
I scanned KerbalConfigEditor with the [Mono Migration Analyzer (MoMA) tool](http://www.mono-project.com/docs/tools+libraries/tools/moma/).
There was one issue:

> MoMA Scan Results
> Scan Date: 1/23/2015 8:43:53 PM
> MoMA Definitions: Mono 2.8 (4.0 Profile)
> 
> For descriptions of issues, see [MoMA Issue Descriptions](http://www.mono-project.com/docs/tools+libraries/tools/moma/issue-descriptions/#monotodo).
> 
> | Assembly | Version | Missing | Not Implemented | Todo | P/Invoke |
> | --- | --- | --- | --- | --- | --- |
> | `Kerbal Config Editor.exe` | 1.0.2.0 | 0 | 0 | 1 | 0 |
> 
> > | Calling Method | Method with [MonoTodo] | Reason |
> > | --- | --- | --- |
> > | `void saveValuesButton_Click (Object, EventArgs)` | `bool Type.op_Equality (Type, Type)` | Implement it properly once 4.0 impl details are known. |

This will probably _not_ cause KCE to fail on Mono, so low priority.

**Comment by IRnifty** [comment]
If and when KCE is migrated to Mono, I'll be sure to test this and change the implementation if necessary.
